# MySQL datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/SPCA1

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=update

# Helpful during development
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.max-size=16
